export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";

export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_CART = "DELETE_CART";

export const SORT_BY_PRICE = "SORT_BY_PRICE";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
