export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";

export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_CART = "DELETE_CART";
